# Generated by Django 5.0 on 2025-01-01 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_doctor_age_remove_doctor_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告標題')),
                ('content', models.TextField(verbose_name='公告內容')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='公告日期')),
                ('author', models.CharField(max_length=100, verbose_name='公告發布者')),
            ],
        ),
    ]
